[theme]
primaryColor="#f63366"
backgroundColor="#0e1117"
secondaryBackgroundColor="#0B0D16"
textColor="#fafafa"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats = false
