name: Main pages

on:   
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run -> home, about'
        required: true
        default: 'all'
jobs:
  home:
    name: Build page_home
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'home' || github.event.inputs.job == 'all' }}
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: "page_main"
      BASEFOLDER: "main"
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file ${{ env.BASEFOLDER }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/xtraorbitals/${{ env.IMAGE_NAME }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:latest
        docker push $IMAGE_ID:latest

  about:
    name: Build page_about
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'about' || github.event.inputs.job == 'all' }}
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: "page_about"
      BASEFOLDER: "about"
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file ${{ env.BASEFOLDER }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/xtraorbitals/${{ env.IMAGE_NAME }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
